// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2zKhiGF-xzfsW6hC3EdIMzKWtOIgwFL8',
    appId: '1:318906357124:web:fe5e68d6c017175e76f9d1',
    messagingSenderId: '318906357124',
    projectId: 'meet-d88a7',
    authDomain: 'meet-d88a7.firebaseapp.com',
    storageBucket: 'meet-d88a7.firebasestorage.app',
    measurementId: 'G-6RGKR9D67K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDefixQDXDjVI3KZMGqKDQPPHhwmjW8xiU',
    appId: '1:318906357124:android:ca7d0ffd8e4c970476f9d1',
    messagingSenderId: '318906357124',
    projectId: 'meet-d88a7',
    storageBucket: 'meet-d88a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg-cWP3zuZCRSZC-YGfiDK389c046b7K4',
    appId: '1:318906357124:ios:03e02fb782fa0fa876f9d1',
    messagingSenderId: '318906357124',
    projectId: 'meet-d88a7',
    storageBucket: 'meet-d88a7.firebasestorage.app',
    iosBundleId: 'com.meet.app.meet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg-cWP3zuZCRSZC-YGfiDK389c046b7K4',
    appId: '1:318906357124:ios:03e02fb782fa0fa876f9d1',
    messagingSenderId: '318906357124',
    projectId: 'meet-d88a7',
    storageBucket: 'meet-d88a7.firebasestorage.app',
    iosBundleId: 'com.meet.app.meet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2zKhiGF-xzfsW6hC3EdIMzKWtOIgwFL8',
    appId: '1:318906357124:web:a4fe2d893ec915cd76f9d1',
    messagingSenderId: '318906357124',
    projectId: 'meet-d88a7',
    authDomain: 'meet-d88a7.firebaseapp.com',
    storageBucket: 'meet-d88a7.firebasestorage.app',
    measurementId: 'G-ZV5V44SPHR',
  );
}
